{% set name = "clusterpy" %}
{% set camelName = "clusterPy" %}
{% set version = "0.9.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ camelName }}-{{ version }}.tar.gz
  sha256: 6e46749b806dbf098c78de3c991ba146820ac428ca9ad1882369672076cd4fa2

build:
  skip: True  # [py3k]
  number: 1003
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python

  run:
    - python
    - numpy

test:
  imports:
    - clusterpy
    - clusterpy.core
    - clusterpy.core.data
    - clusterpy.core.geometry
    - clusterpy.core.toolboxes
    - clusterpy.core.toolboxes.cluster
    - clusterpy.core.toolboxes.cluster.componentsAlg

about:
  home: http://www.rise-group.org/section/Software/clusterPy/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: 'Library of spatially constrained clustering algorithms'
  dev_url: https://code.google.com/archive/p/clusterpy/source/default/source
  doc_url: http://www.rise-group.org/risem/clusterpy/index.html

extra:
  recipe-maintainers:
    - pmlandwehr
