travis:
  secure:
    BINSTAR_TOKEN: jIWjm/qv17QA2hzui3RT738d4kF6RLWQAHdrDeOwyL4rH9qjGaZ4FsbigeMwytNWMG9cSMSMTMH2Z5gdUgF+iyOisHIswU3ZIDKix/op3v3fpKiRHwxICtdrIOU5PZFS7vBLMwQRBVKfPn8Ia2v2uOaEO9qfK2hE5djdW9vZI9GOktceIOxu+FBPwuDgj3s1s7KVTwW7jUA0DYkLq+nXH7NvHsNfU/vXQgAMJ+DFHFxyuPbJ/ljEJpVLhsrJyy4Uem3SbF2LqgbkCGwxKJoLFweI1wND5oCAtIYiyRyFTKnOsBp98x3R0hzuUNIqhgPE7nvfJ4PXDQcTqdDtZi3Y437wwq8LSc+PotdrUZs+YX2oPLsKAV1a/l8kVZBDonGn/OHw951ANNeYTyRAUwc+87OGyr5/i6AaClCaPUHo5WpDQr6M7jnqmLrOCp7HBAAFsBnsi5l7JhU1QSDAJfjVyWegBi2TG6IBs0P3cbHsohMf4jrrTf8huwBTLgvBPZJe912uCK9MnKjfRtNIVsMwJ0W8aq1rfnAE+NjB3hHiX2ciokOprNg/gA/e/NScL51fflC26QC8xIzcYDbDh09QSv7DP95XkSp+NVFuggHDvDgXbb5OwuJh4PIfJY85FPrOf5gXPU0x74pNxpXIcRySbcW7oWMiMN0IGXMOtUUj3XA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
